### test usuario de prueba
POST http://localhost:3000/api/usuarios HTTP/1.1
Content-Type: application/json

{
  "nombre": "Julieta Test",
  "edad": 25,
  "ubicacion": "Buenos Aires",
  "avatarUrl": "https://i.pravatar.cc/150",
  "descripcion": "Perfil de prueba para smoke test",
  "compatibilidad": 95,
  "spotifyId": "julia_test_002",
  "topArtistas": [
    { "nombre": "CA7RIEL", "imagenUrl": "https://i.pravatar.cc/80?img=1" },
    { "nombre": "Mon Laferte", "imagenUrl": "https://i.pravatar.cc/80?img=2" },
    { "nombre": "Doja Cat", "imagenUrl": "https://i.pravatar.cc/80?img=3" }
  ],
  "topCanciones": [
    { "titulo": "Mi Diosa", "artista": "CA7RIEL", "coverUrl": "https://i.pravatar.cc/56?img=4" },
    { "titulo": "Amor Completo", "artista": "Mon Laferte", "coverUrl": "https://i.pravatar.cc/56?img=5" },
    { "titulo": "Ain't Shit", "artista": "Doja Cat", "coverUrl": "https://i.pravatar.cc/56?img=6" }
  ],
  "redes": {
    "instagram": "https://instagram.com",
    "spotify": "https://open.spotify.com",
    "twitter": "https://twitter.com"
  }
}

###
GET http://localhost:3000/api/usuarios/perfil/6a38871e5662a3b5b9f86102 HTTP/1.1

### Traer perfil Spotify
GET http://localhost:3000/api/usuarios/perfil/6a38871e5662a3b5b9f86102/spotify HTTP/1.1